AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless MVC Website => flagscript.technology

Parameters:

  AspNetCoreEnvironment:
    Type: String
    AllowedValues:
      - Development
      - Staging
      - Production
    Default: Development
    Description: Value to use for bootstraping ASPNETCORE_ENVIRONMENT environment variable.

Globals:
  Function:
    Runtime: dotnetcore2.1
    MemorySize: 256
    Timeout: 30

Resources:

  FlagscriptLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Flagscript.CiCdTest::Flagscript.CiCdTest.TestFunction::SayHello
      CodeUri: 
      Policies: 
        - AWSLambdaFullAccess
      Environment: 
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref AspNetCoreEnvironment
