version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      # Add .NET Core SDK tools
      - export PATH="$PATH:/root/.dotnet/tools"
      # Setup dotnet cli aws extensions
      - dotnet tool install -g Amazon.Lambda.Tools
    finally:
      # List Environment Variables
      # - printenv
      # Print CodeBuild Vars
      - echo $PIPELINE_BUCKET
      - echo $APPLICATION_NAME
  build:
    commands:
      - >
        dotnet -d lambda package-ci 
        -pl ./src/Flagscript.CiCdTest/Flagscript.CiCdTest.csproj 
        -c Release 
        -f netcoreapp2.1
        -t ./app-cloudformation.yml
        -ot ./output-templates/app-cloudformation.yml
        -sb $PIPELINE_BUCKET
        -sp $APPLICATION_NAME/package-ci

artifacts:
  files: 
    - ./src/Flagscript.CiCdTest/bin/Release/netcoreapp2.1/*
