version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      # Setup dotnet cli aws extensions
      - dotnet tool install -g Amazon.Lambda.Tools
    finally:
      # List Environment Variables
      - printenv
  build:
    commands:
      - dotnet build ./src/Flagscript.CiCdTest/Flagscript.CiCdTest.csproj -c Release -f netcoreapp2.1

artifacts:
  files: 
    - ./src/Flagscript.CiCdTest/bin/Release/*