AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless MVC Website => flagscript.technology

Parameters:

  ApplicationName:
    AllowedPattern: '[a-z-]+'
    ConstraintDescription: must only contain lowercase letters and hyphens
    Default: flagscript-tech-website
    Description: Name of the dotnet application to deploy
    Type: String
    MinLength: 5
    MaxLength: 30

  AspNetCoreEnvironment:
    Type: String
    AllowedValues:
      - Development
      - Staging
      - Production
    Default: Development
    Description: Value to use for bootstraping ASPNETCORE_ENVIRONMENT environment variable.

Globals:
  Function:
    Runtime: dotnetcore2.1
    MemorySize: 256
    Timeout: 30

Resources:

  FlagscriptLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-lambda-SayHello
      Handler: Flagscript.CiCdTest::Flagscript.CiCdTest.TestFunction::SayHello
      CodeUri: 
      Policies: 
        - AWSLambdaFullAccess
      Environment: 
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref AspNetCoreEnvironment
