AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless MVC Website => flagscript.technology

Parameters:

  ApplicationName:
    AllowedPattern: '[a-z-]+'
    ConstraintDescription: must only contain lowercase letters and hyphens
    Default: flagscript-tech-website
    Description: Name of the dotnet application to deploy
    Type: String
    MinLength: 5
    MaxLength: 30

  AspNetCoreEnvironment:
    Type: String
    AllowedValues:
      - Development
      - Staging
      - Production
    Default: Development
    Description: Value to use for bootstraping ASPNETCORE_ENVIRONMENT environment variable.

  StageWebsiteDomainName:
    Type: String

  CertificateArn:
    Type: String

Globals:
  Function:
    Runtime: dotnetcore2.1
    MemorySize: 256
    Timeout: 30

Resources:

  FlagscriptLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-lambda-mvc
      Handler: Flagscript.CiCdTest::Flagscript.CiCdTest.LambdaEntryPoint::FunctionHandlerAsync
      CodeUri: 
      Policies: 
        - AWSLambdaFullAccess
      Environment: 
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref AspNetCoreEnvironment
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootResource:
          Type: Api
          Properties:
            Path: /
            Method: ANY

  WebsiteDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn: !Ref CertificateArn
      DomainName: !Ref StageWebsiteDomainName
      EndpointConfiguration:
        Types:
          - REGIONAL

  WebsiteDomainBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref WebsiteDomainName
      RestApiId: !Ref ServerlessRestApi
      Stage: Prod

  WebsiteDomain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: ZKMUOIZE0RJK4
      RecordSets:
      - Name: !Ref StageWebsiteDomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt WebsiteDomainName.RegionalDomainName
          HostedZoneId: !GetAtt WebsiteDomainName.RegionalHostedZoneId    

Outputs:
    MvcUrl:
      Description: MVC Website endpoint URL for Prod environment
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
